version: '3'

services:
  master:
    container_name: otus_sn_mysql_master
    build:
      context: ./docker/mysql/master
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/master/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/master/data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '1.0'
  slave1:
    container_name: otus_sn_mysql_slave1
    build:
      context: ./docker/mysql/slave1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/slave1/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/slave1/data:/var/lib/mysql
    ports:
      - "33062:3306"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '1.0'
  slave2:
    container_name: otus_sn_mysql_slave2
    build:
      context: ./docker/mysql/slave2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/slave1/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/slave2/data:/var/lib/mysql
    ports:
      - "33063:3306"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '1.0'
  redis:
    container_name: otus_sn_redis
    build:
      context: ./docker/redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - internal
  rabbitmq:
    container_name: otus_sn_rabbitmq
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
  app1:
    container_name: otus_sn_app1
    restart: always
    build:
      context: .
    volumes:
      - ./docker/app/env:/var/app/.env
    ports:
      - "18085:8085"
    networks:
      - internal
  app2:
    container_name: otus_sn_app2
    restart: always
    build:
      context: .
    volumes:
      - ./docker/app/env:/var/app/.env
    ports:
      - "18086:8085"
    networks:
      - internal
  app3:
    container_name: otus_sn_app3
    restart: always
    build:
      context: .
    volumes:
      - ./docker/app/env:/var/app/.env
    ports:
      - "18087:8085"
    networks:
      - internal
networks:
  internal:
    driver: bridge