version: '3'

services:
  consul-node1:
    image: bitnami/consul:1.12.0
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - 'consul-node1_data:/bitnami'
    networks:
      - otus_sn_network

  consul-node2:
    image: bitnami/consul:1.12.0
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
    volumes:
      - 'consul-node2_data:/bitnami'
    networks:
      - otus_sn_network

  consul-node3:
    image: bitnami/consul:1.12.0
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
    volumes:
      - 'consul-node3_data:/bitnami'
    networks:
      - otus_sn_network
  app:
    container_name: otus_sn_app
    build:
      context: .
    restart: on-failure
    ports:
      - "8085:8085"
    networks:
      - otus_sn_network
    depends_on:
      - master
      - slave1
      - slave2
      - rabbitmq
      - redis
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
  master:
    container_name: otus_sn_mysql_master
    build:
      context: ./docker/mysql/master
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/master/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/master/data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - otus_sn_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  slave1:
    container_name: otus_sn_mysql_slave1
    build:
      context: ./docker/mysql/slave1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/slave1/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/slave1/data:/var/lib/mysql
    ports:
      - "33062:3306"
    networks:
      - otus_sn_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    depends_on:
      - master
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  slave2:
    container_name: otus_sn_mysql_slave2
    build:
      context: ./docker/mysql/slave2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/slave1/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/slave2/data:/var/lib/mysql
    ports:
      - "33063:3306"
    networks:
      - otus_sn_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    depends_on:
      - master
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  redis:
    container_name: otus_sn_redis
    build:
      context: ./docker/redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - otus_sn_network
  rabbitmq:
    container_name: otus_sn_rabbitmq
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - otus_sn_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
networks:
  otus_sn_network:
    external: false
    name: otus_sn_network
volumes:
  consul-node1_data:
    driver: local
  consul-node2_data:
    driver: local
  consul-node3_data:
    driver: local