version: '3'

services:
  master:
    container_name: otus_sn_mysql_master
    build:
      context: ./docker/mysql/master
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/master/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/master/data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  slave1:
    container_name: otus_sn_mysql_slave1
    depends_on:
      - master
    build:
      context: ./docker/mysql/slave1
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/slave1/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/slave1/data:/var/lib/mysql
    ports:
      - "33062:3306"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  slave2:
    container_name: otus_sn_mysql_slave2
    depends_on:
      - master
    build:
      context: ./docker/mysql/slave2
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/slave1/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/slave2/data:/var/lib/mysql
    ports:
      - "33063:3306"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    container_name: otus_sn_redis
    build:
      context: ./docker/redis
    restart: on-failure
    ports:
      - "16379:6379"
    networks:
      - internal
  rabbitmq:
    container_name: otus_sn_rabbitmq
    image: rabbitmq:management-alpine
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app1:
    container_name: otus_sn_app1
    depends_on:
      - master
      - slave1
      - slave2
      - rabbitmq
      - redis
      - haproxy
    restart: on-failure
    build:
      context: .
    volumes:
      - ./docker/app/env:/var/app/.env
    ports:
      - "18085:8085"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app2:
    container_name: otus_sn_app2
    depends_on:
      - master
      - slave1
      - slave2
      - rabbitmq
      - redis
      - haproxy
      - app1
    restart: on-failure
    build:
      context: .
    volumes:
      - ./docker/app/env:/var/app/.env
    ports:
      - "18086:8085"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app3:
    container_name: otus_sn_app3
    depends_on:
      - master
      - slave1
      - slave2
      - rabbitmq
      - redis
      - haproxy
      - app1
      - app2
    restart: on-failure
    build:
      context: .
    volumes:
      - ./docker/app/env:/var/app/.env
    ports:
      - "18087:8085"
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085" ]
      interval: 30s
      timeout: 10s
      retries: 5
  haproxy:
    depends_on:
      - master
      - slave1
      - slave2
    image: haproxy:2.4
    container_name: otus_sn_haproxy
    restart: on-failure
    networks:
      - internal
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8404:8404"
      - "33064:3306"
  nginx:
    depends_on:
      - app1
      - app2
      - app3
    image: nginx:1.21
    container_name: otus_sn_nginx
    restart: on-failure
    networks:
      - internal
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:80"
      - "9001:8080"
networks:
  internal:
    driver: bridge